#!/bin/bash
echo ""
echo "***************"
echo "Welcome to your first time setup!"
echo "I will attempt to download all of your favorite programs"
echo "***************"
echo ""
sudo snap install spotify
sudo apt install clementine
sudo apt install soundconverter
sudo snap install libreoffice
sudo snap install android-studio
sudo snap install eclipse --classic
sudo apt install gnome-tweaks
sudo apt install arc-theme
sudo snap install code --classic
sudo snap install vlc
sudo snap install electron-mail
sudo snap install discord --classic
sudo apt install steam-installer
echo ""
echo "***************"
echo "All finished! :)"
echo "Welcome to your new OS"
echo "***************"
echo ""
